-- ================================================
-- Demo 独立数据库表（在 Supabase SQL Editor 中执行）
-- 在 supabase.io → SQL Editor → 粘贴 → Run
-- ================================================

-- 1. 用户表 (demo)
CREATE TABLE IF NOT EXISTS demo_hwm_users (
  uid TEXT PRIMARY KEY,
  user_data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 周计划表 (demo)
CREATE TABLE IF NOT EXISTS demo_hwm_workplans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  week_id TEXT NOT NULL,
  plan_data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(username, week_id)
);

-- 3. 员工表 (demo)
CREATE TABLE IF NOT EXISTS demo_hwm_employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id TEXT UNIQUE,
  data JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 岗位表 (demo)
CREATE TABLE IF NOT EXISTS demo_hwm_jobdesc (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT UNIQUE,
  data JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 收藏表 (demo)
CREATE TABLE IF NOT EXISTS demo_hwm_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(username, item_id, item_type)
);

-- ===== 以下可选：把现有正式数据作为 demo 初始数据 =====
-- INSERT INTO demo_hwm_users SELECT * FROM hwm_users
--   WHERE uid IN ('谭晨航','admin','demo');
-- INSERT INTO demo_hwm_workplans SELECT * FROM hwm_workplans
--   WHERE username IN ('谭晨航','admin','demo');
