// ★ V0.6.1.gl: Demo 花名册 — HWM-花名册（2026-6-AI专用）自动生成
window.__DATA_VERSION__ = 'demo-20260715-v2';
var __PRELOADED_EMPLOYEES__ = [
  {
    "empId": "HW0001",
    "name": "韩铁工",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "董事长",
    "joinDate": "2017-01-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0002",
    "name": "刘星梦",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "管理者代表兼体系部经理",
    "joinDate": "2017-06-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0003",
    "name": "李欣华",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "总监",
    "joinDate": "2017-06-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0005",
    "name": "孙颖",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "总经理",
    "joinDate": "2018-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0006",
    "name": "杨春晓",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "体系专员",
    "joinDate": "2019-04-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0008",
    "name": "朱本双",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2019-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0009",
    "name": "李二燕",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "样品制作员",
    "joinDate": "2019-08-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0010",
    "name": "王蕾",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2019-09-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0011",
    "name": "朱颜芳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2019-09-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0018",
    "name": "王祖和",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "主管",
    "joinDate": "2020-04-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0022",
    "name": "吴雪琼",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "组长",
    "joinDate": "2020-05-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0023",
    "name": "赵虎",
    "status": "已转正",
    "center": "营销中心",
    "dept": "技术服务部",
    "position": "技术服务工程师",
    "joinDate": "2020-07-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0024",
    "name": "王珊珊",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "文控专员",
    "joinDate": "2020-07-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0026",
    "name": "杨鹏飞",
    "status": "已转正",
    "center": "营销中心",
    "dept": "技术服务部",
    "position": "技术服务部主管",
    "joinDate": "2020-08-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0029",
    "name": "陆娟娟",
    "status": "已转正",
    "center": "供应链及物流中心",
    "dept": "采购部",
    "position": "采购专员",
    "joinDate": "2020-10-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0036",
    "name": "王宁",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "助理工程师",
    "joinDate": "2021-02-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0037",
    "name": "张向利",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "总监",
    "joinDate": "2021-02-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0039",
    "name": "葛师师",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "研发部经理",
    "joinDate": "2021-02-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0040",
    "name": "赵怡红",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2021-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0001",
    "name": "荣相景",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0002",
    "name": "史娜娜",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0042",
    "name": "洪传跃",
    "status": "已转正",
    "center": "人力资源部",
    "dept": "人力资源部",
    "position": "经理",
    "joinDate": "2021-03-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0007",
    "name": "田寿月",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "样品制作员",
    "joinDate": "2021-03-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0049",
    "name": "徐双双",
    "status": "已转正",
    "center": "营销中心",
    "dept": "商务部",
    "position": "商务专员",
    "joinDate": "2021-04-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0008",
    "name": "郑小雪",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2021-04-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0009",
    "name": "朱广花",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2021-04-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0050",
    "name": "曹敏",
    "status": "已转正",
    "center": "营销中心",
    "dept": "销售行政部",
    "position": "销售行政专员",
    "joinDate": "2021-04-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0055",
    "name": "于琳",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2021-05-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0056",
    "name": "李如秀",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2021-05-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0057",
    "name": "荣芝",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2021-05-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0059",
    "name": "尤亚君",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "总经理助理兼行政部副经理",
    "joinDate": "2021-05-31",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0061",
    "name": "王慧颖",
    "status": "已转正",
    "center": "营销中心",
    "dept": "销售行政部",
    "position": "销售行政主管",
    "joinDate": "2021-06-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0063",
    "name": "葛树刚",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "经理",
    "joinDate": "2021-06-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0067",
    "name": "蒙晓峰",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2021-06-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0070",
    "name": "刘路英",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "全国销售经理",
    "joinDate": "2021-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0075",
    "name": "赵凯",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "商务部代理经理",
    "joinDate": "2021-07-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0077",
    "name": "谢安文",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "实验室测试员",
    "joinDate": "2021-07-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0079",
    "name": "齐娜娜",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2021-07-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0080",
    "name": "李雪",
    "status": "已转正",
    "center": "研发中心",
    "dept": "注册部",
    "position": "注册专员",
    "joinDate": "2021-07-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0087",
    "name": "张傲雪",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2021-08-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0016",
    "name": "刘会",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-08-10",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0018",
    "name": "朱倩倩",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-08-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0019",
    "name": "施万秀",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-08-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0088",
    "name": "徐亮",
    "status": "已转正",
    "center": "财务部",
    "dept": "财务部",
    "position": "经理",
    "joinDate": "2021-08-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0092",
    "name": "胡金凤",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2021-08-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0022",
    "name": "张翠容",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-08-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0025",
    "name": "丁萍",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-09-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0027",
    "name": "管邦燕",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-09-27",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0028",
    "name": "陈丹丹",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-09-29",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0029",
    "name": "张正梅",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-10-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0030",
    "name": "张四红",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-10-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0097",
    "name": "王鑫",
    "status": "已转正",
    "center": "供应链及物流中心",
    "dept": "仓管部",
    "position": "仓管员",
    "joinDate": "2021-10-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "劳务人员",
    "name": "胡玉兰",
    "status": "已转正",
    "center": "总经办",
    "dept": "行政管理部",
    "position": "保洁（劳务工）",
    "joinDate": "2021-10-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0098",
    "name": "钟斌",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2021-10-20",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0103",
    "name": "周超",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2021-11-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0034",
    "name": "肖静茹",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2021-12-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0037",
    "name": "荣翔",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2021-12-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0107",
    "name": "温豪",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "北大区经理",
    "joinDate": "2021-12-27",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0038",
    "name": "葛艳谱",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2022-01-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "SZ0001",
    "name": "杨丽玉",
    "status": "已转正",
    "center": "人力资源部",
    "dept": "人事行政部",
    "position": "人事行政经理",
    "joinDate": "2022-02-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0039",
    "name": "田梅艳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-02-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0111",
    "name": "陆妍妍",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "样品制作员",
    "joinDate": "2022-02-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0042",
    "name": "张悦",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-03-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0045",
    "name": "何礼婷",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-03-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0113",
    "name": "强培培",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "生产文员",
    "joinDate": "2022-03-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0114",
    "name": "钟雅洁",
    "status": "已转正",
    "center": "总经办",
    "dept": "行政管理部",
    "position": "专员",
    "joinDate": "2022-03-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0115",
    "name": "郭峰",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "工艺工程师",
    "joinDate": "2022-03-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0117",
    "name": "冯瑜琪",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "省区经理",
    "joinDate": "2022-04-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0121",
    "name": "金辉",
    "status": "已转正",
    "center": "总经办",
    "dept": "行政管理部",
    "position": "IT工程师",
    "joinDate": "2022-04-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0128",
    "name": "赵小姣",
    "status": "已转正",
    "center": "人力资源部",
    "dept": "人力资源部",
    "position": "高级人事专员",
    "joinDate": "2022-05-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0048",
    "name": "张媛媛",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-05-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0049",
    "name": "宋金燕",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-05-27",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0137",
    "name": "崔自信",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "销售专员",
    "joinDate": "2022-07-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0141",
    "name": "张国敬",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "设备技术员",
    "joinDate": "2022-08-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "劳务人员",
    "name": "陈新芳",
    "status": "已转正",
    "center": "总经办",
    "dept": "行政管理部",
    "position": "保洁（劳务工）",
    "joinDate": "2022-08-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0143",
    "name": "余梦婷",
    "status": "已转正",
    "center": "财务部",
    "dept": "财务部",
    "position": "会计",
    "joinDate": "2022-08-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0052",
    "name": "徐可可",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-08-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0054",
    "name": "高易梅",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-09-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0151",
    "name": "马玉纤",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2022-09-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0154",
    "name": "陈曦",
    "status": "已转正",
    "center": "研发中心",
    "dept": "注册部",
    "position": "注册工程师",
    "joinDate": "2022-10-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0155",
    "name": "朱玉洁",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2022-10-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0157",
    "name": "王慰",
    "status": "已转正",
    "center": "供应链及物流中心",
    "dept": "采购部",
    "position": "采购工程师",
    "joinDate": "2022-11-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0056",
    "name": "李传月",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-11-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0158",
    "name": "李文正",
    "status": "已转正",
    "center": "营销中心",
    "dept": "技术服务部",
    "position": "技术服务专员",
    "joinDate": "2022-11-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0057",
    "name": "荣相容",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2022-11-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0160",
    "name": "杨成",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "董事长助理、代国内营销总监",
    "joinDate": "2023-01-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0059",
    "name": "刘苗苗",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "生产文员",
    "joinDate": "2023-02-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0162",
    "name": "王小兰",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-02-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0163",
    "name": "高艳红",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-02-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0165",
    "name": "张力文",
    "status": "已转正",
    "center": "财务部",
    "dept": "财务部",
    "position": "资金税务会计",
    "joinDate": "2023-02-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0063",
    "name": "胡长红",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2023-02-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0064",
    "name": "葛文华",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0069",
    "name": "陈晶",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-03-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0169",
    "name": "葛韵",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2023-03-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0071",
    "name": "王露桃",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "组长",
    "joinDate": "2023-03-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0172",
    "name": "何颖颖",
    "status": "已转正",
    "center": "营销中心",
    "dept": "商务部",
    "position": "商务主管",
    "joinDate": "2023-04-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0175",
    "name": "石崇香",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "测试技术员",
    "joinDate": "2023-04-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0177",
    "name": "杨笑云",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-05-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0178",
    "name": "曹静",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-05-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0180",
    "name": "刘浩东",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "技术服务工程师",
    "joinDate": "2023-06-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0183",
    "name": "胡永恒",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "技术服务工程师",
    "joinDate": "2023-06-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0188",
    "name": "刘琴",
    "status": "已转正",
    "center": "营销中心",
    "dept": "商务部",
    "position": "市场准入经理",
    "joinDate": "2023-07-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0189",
    "name": "胡猛窕",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-07-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0074",
    "name": "耿言双",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-07-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0190",
    "name": "曹坤",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "安全员兼设备管理员",
    "joinDate": "2023-07-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0192",
    "name": "张慢慢",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-08-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0194",
    "name": "周斌",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "PMC",
    "joinDate": "2023-08-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0195",
    "name": "刘年",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2023-08-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0197",
    "name": "耿洋",
    "status": "已转正",
    "center": "供应链及物流中心",
    "dept": "仓管部",
    "position": "仓管员",
    "joinDate": "2023-08-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0204",
    "name": "谭晨航",
    "status": "已转正",
    "center": "人力资源部",
    "dept": "人力资源部",
    "position": "人力资源总监",
    "joinDate": "2023-09-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0076",
    "name": "胡梦雨",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-09-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0205",
    "name": "李翔",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "省区经理",
    "joinDate": "2023-09-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0206",
    "name": "崔翔",
    "status": "已转正",
    "center": "研发中心",
    "dept": "工程技术部",
    "position": "工艺工程师",
    "joinDate": "2023-09-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0080",
    "name": "蔡成红",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-10-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0208",
    "name": "李洪海",
    "status": "已转正",
    "center": "营销中心",
    "dept": "医学市场部",
    "position": "医学经理",
    "joinDate": "2023-10-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "SZ0006",
    "name": "陈冬银",
    "status": "已转正",
    "center": "研发中心",
    "dept": "苏州研发中心",
    "position": "注册主管",
    "joinDate": "2023-11-02",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0210",
    "name": "黄明敏",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2023-11-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0211",
    "name": "王泷杰",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "销售专员",
    "joinDate": "2023-11-27",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0213",
    "name": "朱传英",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-12-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0214",
    "name": "刘同云",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2023-12-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0081",
    "name": "武春萍",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2023-12-18",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0215",
    "name": "林娟",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "省区经理",
    "joinDate": "2023-12-18",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "SZ0008",
    "name": "张宁",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "结构工程师",
    "joinDate": "2024-01-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0216",
    "name": "哈劢克",
    "status": "已转正",
    "center": "供应链及物流中心",
    "dept": "仓管部",
    "position": "仓管员",
    "joinDate": "2024-01-02",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0217",
    "name": "刘阳",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2024-01-02",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0218",
    "name": "段艳艳",
    "status": "已转正",
    "center": "",
    "dept": "",
    "position": "",
    "joinDate": "2024-01-02",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0221",
    "name": "王帅",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2024-01-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0082",
    "name": "胡银银",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-01-12",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0083",
    "name": "郭婷婷",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-01-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0084",
    "name": "殷小雪",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-02-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0085",
    "name": "宫丽",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-02-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0086",
    "name": "欧永茗",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-02-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0225",
    "name": "周双双",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-02-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0226",
    "name": "张雪",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-02-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0088",
    "name": "钟荣荣",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-02-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0227",
    "name": "康术贤",
    "status": "已转正",
    "center": "财务部",
    "dept": "财务部",
    "position": "成本会计",
    "joinDate": "2024-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0091",
    "name": "陈杰",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-03-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0094",
    "name": "刘彦春",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-03-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0095",
    "name": "李艳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-03-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0102",
    "name": "王莹莹",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-03-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0233",
    "name": "刘雨静",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-03-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0108",
    "name": "赵纹文",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-03-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0236",
    "name": "张杰妹",
    "status": "已转正",
    "center": "研发中心",
    "dept": "注册部",
    "position": "注册工程师",
    "joinDate": "2024-04-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0109",
    "name": "张艳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-04-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0238",
    "name": "刘妍",
    "status": "已转正",
    "center": "研发中心",
    "dept": "采购部",
    "position": "采购工程师",
    "joinDate": "2024-04-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0113",
    "name": "许珍",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "质检组长",
    "joinDate": "2024-04-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0114",
    "name": "杨传秀",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-04-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0115",
    "name": "李玲玉",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-04-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0116",
    "name": "陈梅",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-04-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0239",
    "name": "司五梅",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2024-04-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0118",
    "name": "王伟爱",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-04-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0240",
    "name": "王蝶",
    "status": "已转正",
    "center": "营销中心",
    "dept": "商务部",
    "position": "商务专员",
    "joinDate": "2024-05-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0242",
    "name": "朱艳玲",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-05-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0245",
    "name": "张照懿",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2024-05-22",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0246",
    "name": "刘娜娜",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-06-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0249",
    "name": "马新月",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-06-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0121",
    "name": "莫芳",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量管理部",
    "position": "品质工程师",
    "joinDate": "2024-06-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0250",
    "name": "马军",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "质检组长",
    "joinDate": "2024-06-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0251",
    "name": "李海艳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-06-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0257",
    "name": "张乃梅",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2024-07-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0258",
    "name": "张敏捷",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "实验室测试员",
    "joinDate": "2024-07-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0260",
    "name": "陶斯楚",
    "status": "已转正",
    "center": "营销中心",
    "dept": "海外销售",
    "position": "海外销售专员",
    "joinDate": "2024-07-30",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0261",
    "name": "王德瑞",
    "status": "已转正",
    "center": "营销中心",
    "dept": "医学市场部",
    "position": "市场专员",
    "joinDate": "2024-08-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0266",
    "name": "杨光",
    "status": "已转正",
    "center": "研发中心",
    "dept": "工程技术部",
    "position": "工艺工程师",
    "joinDate": "2024-08-28",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0125",
    "name": "敖娜娜",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-09-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0269",
    "name": "吴盼盼",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2024-09-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0126",
    "name": "杨盼盼",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "文控专员",
    "joinDate": "2024-09-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0275",
    "name": "魏骏文",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2024-10-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0278",
    "name": "韩如雷",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "结构工程师",
    "joinDate": "2024-11-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0130",
    "name": "王维燕",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2024-12-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0285",
    "name": "张烁",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "仓管员",
    "joinDate": "2025-02-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0286",
    "name": "顾晓娜",
    "status": "已转正",
    "center": "营销中心",
    "dept": "海外销售",
    "position": "海外销售经理",
    "joinDate": "2025-03-17",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0133",
    "name": "石玉齐",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "摩祖质量部",
    "position": "检验员",
    "joinDate": "2025-03-26",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0134",
    "name": "金昭",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-04-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0140",
    "name": "葛艳南",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-04-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0141",
    "name": "王惠珠",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-04-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0142",
    "name": "张美利",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-04-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0146",
    "name": "程康莉",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-04-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0147",
    "name": "赵雅男",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-05-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0148",
    "name": "陈艳洁",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-05-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0149",
    "name": "郭利利",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-05-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0290",
    "name": "王要",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "高级结构工程师",
    "joinDate": "2025-05-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0291",
    "name": "丁井通",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "电气工程师",
    "joinDate": "2025-05-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0293",
    "name": "张淑芳",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2025-05-19",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0295",
    "name": "王一",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2025-05-29",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0298",
    "name": "尹婷婷",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2025-06-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "MZ0153",
    "name": "陈柳妹",
    "status": "已转正",
    "center": "制造中心",
    "dept": "摩祖生产部",
    "position": "员工",
    "joinDate": "2025-06-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0305",
    "name": "李万娟",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "检验员",
    "joinDate": "2025-07-09",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0306",
    "name": "林海运",
    "status": "已转正",
    "center": "营销中心",
    "dept": "技术服务部",
    "position": "检验员",
    "joinDate": "2025-07-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0308",
    "name": "贾家宁",
    "status": "已转正",
    "center": "营销中心",
    "dept": "医学市场部",
    "position": "市场专员",
    "joinDate": "2025-08-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0309",
    "name": "豆红玲",
    "status": "已转正",
    "center": "制造中心",
    "dept": "生产管理部",
    "position": "员工",
    "joinDate": "2025-08-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0310",
    "name": "董看",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "SQE工程师",
    "joinDate": "2025-08-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0314",
    "name": "徐丽娜",
    "status": "已转正",
    "center": "质量管理中心",
    "dept": "质量管理部",
    "position": "CQE工程师",
    "joinDate": "2025-09-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0315",
    "name": "欧阳宇昕",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "省区经理",
    "joinDate": "2025-09-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0318",
    "name": "汪哲",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "研发助理工程师",
    "joinDate": "2025-09-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0323",
    "name": "刘波",
    "status": "已转正",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "区域经理",
    "joinDate": "2025-09-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0324",
    "name": "杨勇强",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发部",
    "position": "资深结构专家",
    "joinDate": "2025-10-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0325",
    "name": "韩一匡",
    "status": "已转正",
    "center": "营销中心",
    "dept": "海外销售",
    "position": "海外业务专员",
    "joinDate": "2025-12-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0327",
    "name": "王旭开",
    "status": "试用期",
    "center": "研发中心",
    "dept": "研发部",
    "position": "硬件工程师",
    "joinDate": "2026-03-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "HW0328",
    "name": "张文溢",
    "status": "试用期",
    "center": "营销中心",
    "dept": "国内销售",
    "position": "省区经理",
    "joinDate": "2026-04-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  }
];
